# example config using camelCase keys
owner: Bob TBeam

channelUrl: https://www.meshtastic.org/d/#CgUYAyIBAQ

location:
  lat: 35.88888
  lon: -93.88888
  alt: 304

userPrefs:
  region: 1
  isAlwaysPowered: 'true'
  sendOwnerInterval: 2
  screenOnSecs: 31536000
  waitBluetoothSecs: 31536000
