name: Build and publish ubuntu standalone executable

on: workflow_dispatch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Build
        run: |
          pip install pyinstaller
          pip install -r requirements.txt
          pyinstaller -F -n meshtastic meshtastic/__main__.py
      - uses: actions/upload-artifact@v2
        with:
          name: meshtastic
          path: dist
