name: Build and publish mac standalone executable

on: workflow_dispatch

jobs:
  build-and-publish:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Build
        run: |
          pip install pyinstaller
          pip install -r requirements.txt
          pip install .
          pyinstaller -F -n meshtastic --collect-all meshtastic --codesign-identity "Mike Kinney (7Z69U93GMX)" meshtastic/__main__.py
      - uses: actions/upload-artifact@v2
        with:
          name: meshtastic
          path: dist
