name: Linting and Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Uninstall meshtastic
        run: |
          pip3 uninstall meshtastic
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Install meshtastic from local
        run: |
          pip3 install .
          which meshtastic
          meshtastic --version
      - name: Run pylint
        run: pylint meshtastic
      - name: Run tests with pytest
        run: pytest --cov=meshtastic
