name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
      - name: Uninstall meshtastic
        run: |
          pip3 uninstall meshtastic
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Install meshtastic from local
        run: |
          pip3 install .
          which meshtastic
          meshtastic --version
      - name: Run pylint
        run: pylint meshtastic examples/ --ignore-patterns ".*_pb2.pyi?$"
      - name: Check types with mypy
        run: mypy meshtastic/
      - name: Run tests with pytest
        run: pytest --cov=meshtastic
      - name: Generate coverage report
        run: |
          pytest --cov=meshtastic --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: OS, PYTHON
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
      - name: Install meshtastic from local
        run: |
          pip3 install .
          which meshtastic
          meshtastic --version
